config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  resources :products
  resources :mypage, only: [:show]
   # 注文入力・注文作成
  resources :orders, only: [:index, :new, :create] do 
    collection do
      post :confirm   # 注文確認
    end

    member do
      get :complete  # 注文完了
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders

  validates :name, presence: true, uniqueness: true  # 商品名は必須で一意
  validates :price, presence: true                   # 価格は必須
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_admin, except: [:index, :show]
  
  def new
     @product = Product.new
  end
  
  def index
    @products = Product.all
  end
  
  def show
    @product = Product.find(params[:id])
  end
  
  def edit
    @product = Product.find(params[:id])
  end

  def create
      # フォームから送られたデータを元に新しい商品を作成
    @product = Product.new(product_params)

    # データをデータベースに保存する
    if @product.save
      # 成功した場合、トップページへリダイレクト
      redirect_to products_path
    else
      # 失敗した場合、入力内容を保持したままフォームを再表示
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path # 商品詳細にリダイレクト
    else
      render :edit  # 失敗時に編集画面に戻る
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    # 商品一覧にリダイレクト
    redirect_to products_path 
  end

  private

    # ストロングパラメータで、フォームから送信されたデータを許可する
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end

    def check_admin
      unless current_user.admin_flg
        # 管理者でない場合、商品一覧ページにリダイレクト
        redirect_to products_path, alert: '管理者権限が必要です。'
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>商品編集</h1>

<%= form_with(model: @product, local: true) do |f| %>
  <div>
    <%= f.label :name, "商品名" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description, "商品説明" %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price, "価格" %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.submit "更新" %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>商品一覧</h1>
<% if current_user.admin_flg == true %>
  <%= link_to "新規登録", new_product_path %>
<% end %>

<% @products.each do |product| %>
  <div>
    <p>商品名: <%= product.name %></p>
    <p>説明: <%= product.description %></p>
    <p>価格: <%= product.price %> 円</p>
    <%= link_to "詳細", product_path(product.id) %>
  </div>

  <hr>

<% end %>

app/views/products/new.html.erb
<%= form_with model: @product do |f| %>
  <div>
    <%= f.label :name, "商品名" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description, "商品説明" %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :price, "価格" %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.submit "登録" %>
  </div>
<% end %>

app/views/products/show.html.erb
<h1>商品詳細</h1>

<div>
  <p>商品名: <%= @product.name %></p>
  <p>説明: <%= @product.description %></p>
  <p>価格: <%= @product.price %>円</p>
  
  <% if current_user.admin_flg == true %>
      <%= link_to "編集", edit_product_path(@product) %>
      <%= link_to '削除', product_path(@product),  data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' } %>
    <% else %>
      <%= link_to '注文する', new_order_path(product_id:@product.id) %>
  <% end %>
</div>